language:
    python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip3 install virtualenv"
  - "python3 -m \"virtualenv\" venv"
  - ". venv/bin/activate"
  - "pip3 install -r requirements.txt"
# command to run tests
script:
  - python3 -m "nose" --with-cov --cov PittAPI/ --with-timer tests/*
notifications:
    email: false